### ISSUE TITLE
SQLインジェクション脆弱性

### ISSUE THREAD

**Issue by care0717** [r-koike/kuolc1leg#1]
http://kuolc.vastserve.com/1leg/search.php?i=1
の検索ボックスに
' OR 'A'='A
といった文字列を入れると全ての地図が出てきます。
これを悪用するとデータベースを落とすといった行為ができるので
プレースホルダを使うかORMを使うかした方が良いです。

**Comment by r-koike** [comment]
mysqliの静的プレースホルダを導入しました。
以前のような明らかな脆弱性は解消されたはずです。
